onboarding = false

[keys]
prefix = "ctrl+q"

[ui]
agent_panel_sort = "spaces"

[ui.toast]
delivery = "herdr"

[experimental]
switch_ascii_input_source_in_prefix = true

[theme]
name = "catppuccin"
auto_switch = false
